import Head from "next/head";
import Image from "next/image";
import { getFeaturedEvents } from "../dummy-data";
import EventList from "../components/events/event-list";
export default function Home() {
  const featuredEvents = getFeaturedEvents();
  return (
    <div>
      <Head>
        <title>File base routes Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <EventList items={featuredEvents} />
      </main>
    </div>
  );
}
